### ISSUE TITLE
Incorrect route parsing, using the demo snippet

### ISSUE THREAD

**Issue by JulianCataldo** [delucis/astro-og-canvas#11]
Hey!

I've stumbled upon this issue, using `v1.9.0`:

```ts
import { OGImageRoute } from 'astro-og-canvas';

export const { getStaticPaths, get } = OGImageRoute({
	param: 'route',
	// pages: await import.meta.glob('/src/pages/**/*.md', { eager: true }),

	pages: {
		Why: {
			title: 'Why Astro?',
			description:
				'Astro is an all-in-one web framework for building fast, content-focused websites. Learn more.',
		},
		who: {
			title: 'Why Astro?',
			description:
				'Astro is an all-in-one web framework for building fast, content-focused websites. Learn more.',
		},
	},
	getImageOptions: (_path, page) => ({
		title: page.title,
		description: page.description,
	}),
});

console.table(getStaticPaths());
```

yields:

```sh
06:48:14 [astro] reload /src/pages/og/[...route].ts
┌─────────┬─────────────────────┐
│ (index) │       params        │
├─────────┼─────────────────────┤
│    0    │ { route: 'Wh.png' } │
│    1    │ { route: 'wh.png' } │
└─────────┴─────────────────────┘
06:48:15 [getStaticPaths] A `getStaticPaths()` route pattern was matched, but no matching static path was found for requested path `/og/who`.

Possible dynamic routes being matched: src/pages/og/[...route].ts, src/pages/[...page].astro.
06:48:15 [serve]    404                                  /og/who
```

I did get `generateOpenGraphImage` to work separately from the router util.

Thanks for your work 👏

**Comment by AlexTMjugador** [comment]
The default `pathToSlug` function used internally by this package expects page paths to contain an extension (notice how `lastIndexOf` would return -1 if the path does not contain any extension, causing the next `slice` call to trim characters from the path):

https://github.com/delucis/astro-og-canvas/blob/9c9b6d598227efa527559d740f6f8810102895eb/packages/astro-og-canvas/src/routing.ts#L5-L11

To get your example working, you can do one of the following:

1. Add a dummy extension to your route paths, which can be empty (e.g., turn `Why` to `Why.`).
2. Bring your own path-to-slug translation function by setting the `getSlug` parameter in the object passed to `OGImageRoute`, alongside `param`, `pages` and `getImageOptions`. By using a custom function for this, you can relax the extension requirement. Setting `getSlug: (path) => path` would work fine to treat the path as-is, turning off the mangling done by this package.

I've stumbled upon this as well and found the above fixes satisfying.

I hope this helps! :smile:

**Comment by delucis** [comment]
Ah, thanks for diagnosing this @AlexTMjugador! Yes, the default router expects you to be passing content files really, but I guess we could still fix that logic so we only slice at `extIndex` if `extIndex` isn’t `-1`? Happy if someone would like to PR that!

**Comment by AlexTMjugador** [comment]
I think that slicing only if `extIndex` is not -1 is a good solution. Maybe I submit a PR with this change! :smile:
