### ISSUE TITLE
Astro requires `canvaskit-wasm` as a direct dependency

### ISSUE THREAD

**Issue by itsmatteomanf** [delucis/astro-og-canvas#19]
While implementing this package in an Astro static build, I struggled to make `astro-og-canvas` work, until I found, randomly this in the contributor's guide for Astro's Docs site which uses this same package, but works.

https://github.com/withastro/docs/blob/7f93e916436aee2724b99f63436d826f1f345f7e/contributor-guides/astro-maintainers-guide-to-docs.md?plain=1#L164

I guess removing this dependency might be complicated, but what do you all think of adding a note to the readme file?

**Comment by delucis** [comment]
Are you using `pnpm` by any chance? I suspect this is an issue with pnpm’s hoisting, where they are often more strict about how dependencies are installed than npm and Yarn.

**Comment by itsmatteomanf** [comment]
I am, yes.

**Comment by delucis** [comment]
Thanks — will make a suggestion in the PR then to clarify this is a pnpm-specific issue.
