### ISSUE TITLE
[Feature request] Background image option

### ISSUE THREAD

**Issue by vasfvitor** [delucis/astro-og-canvas#32]
Hi, I think a background image option is needed.

If this is fits the project I could work on it and open a pr.  This is the implementation I'm working on, still have to scale up smaller images:
https://github.com/delucis/astro-og-canvas/compare/latest...vasfvitor:astro-og-canvas:bg-image-union

Basically, it changes `bgGradient`  to be `background` and accept either a gradient or a path to file, with the option to resize to fit. But now I'm thinking if it should always resize to fit.

Another way I see is to add a new setting `bgImage`. The issue is that when both are set, it will either overlap `bgGradient` or be overlapped by it.

Thank you.

**Comment by delucis** [comment]
Thanks for the idea! Agree this would be nice to have.

Some thoughts off the top of my head:

- background image should size to fit, but retain it's original aspect ratio
- if maintaining aspect ratio, maybe a need for a cropping strategy? (cover/contain)
- background image should be separate from and on top of the gradient
- background image could support margins to inset it (lets you do stuff like use the gradient background as a frame, or position the background image in just the bottom third etc.)

**Comment by vasfvitor** [comment]
I'm working on it but having trouble finding a way to mix and match what you suggested. Original image is 1920x1080 with RGB gradient.

The issue is that I couldn't find a way to really crop, right now it redraws the gradient over the image when croppping. No biggie, I guess
note: those are illogical side margins
![image](https://github.com/delucis/astro-og-canvas/assets/61759797/ddf94d63-68ab-4f2b-8cd5-e7da0d5af02e)

Alternatively if I set to scale the image taking in account the margin set, if the image is not the same ratio as the og (1200x635), it won't respect margins. Granted, it could be centered and I could be missing something in code as I had to hardcode some stuff to make the demos below. Or it could be a margin to always crop, and another setting to inset with a single value.
![image](https://github.com/delucis/astro-og-canvas/assets/61759797/fb0199de-3abd-4fb8-9636-2bdffebe5163)

I'm looking into CanvasKit and [Skia Fiddles](https://fiddle.skia.org/named/) but I'm yet to find smth useful for those situations

What comes out off the top of your head? (I love this expression haha)

edit: https://github.com/delucis/astro-og-canvas/compare/latest...vasfvitor:astro-og-canvas:feat-bg-crop-cover
I added `salt` temporally to avoid having to clean up the cache every time I make a change to source and don't update params. Now I have to clean once in a while XD

**Comment by fviolette** [comment]
Very nice [vasfvitor](https://github.com/vasfvitor)! Looking forward to this enhancement in an upcoming release, thanks to both of you for your work 👍

**Comment by vasfvitor** [comment]
@fviolette could you give a bit of insight on your use case? and if you have any ideas, I'd like to hear!

**Comment by delucis** [comment]
Sorry not to get back earlier @vasfvitor! Amazing progress here — taking a look in detail now.

**Comment by fviolette** [comment]
@vasfvitor Nothing too fancy on my side, just generating the usual dynamic image preview for docs.
It is just that our design team formulated several proposals, the best happen to require a background image versus a simple background color or gradient :-)

**Comment by vasfvitor** [comment]
@delucis no biggie! thank you
