### ISSUE TITLE
__dirname is not defined in ES module scope (doesn't work with pnpm)

### ISSUE THREAD

**Issue by stereobooster** [delucis/astro-og-canvas#54]
**Example**: https://github.com/stereobooster/astro-og-canvas-example

Error:

```
pnpm build
...
__dirname is not defined in ES module scope
  Stack trace:
    at file:///astro-og-canvas-example/dist/chunks/prerender_UQoVfpFk.mjs:8106:43
 ELIFECYCLE  Command failed with exit code 1.
```

**Comment by delucis** [comment]
Hmm, interesting. Astro’s own docs are built with Starlight and use this. Same for https://astro-embed.netlify.app/ following the guide here: https://hideoo.dev/notes/starlight-og-images

So it definitely works in some circumstances.

Will try to get your example running on StackBlitz (GitHub outage is preventing that right now)

**Comment by stereobooster** [comment]
Maybe it's due to `pnpm`?

**UPD**: yes, just tried - with `npm` it works

**Comment by delucis** [comment]
Interesting. Not sure it’s _just_ that — Astro’s Docs are also using `pnpm`.

Could you share some more details of your environment? Operating system and Node version for example?

**Comment by stereobooster** [comment]
Sure:

```
node -v: v18.17.1
pnpm -v: 8.6.12
MacOS: 14.1.1
```

**Comment by stereobooster** [comment]
This is not OS specific. Here is the same result with Ubuntu https://github.com/stereobooster/astro-og-canvas-example/actions/runs/8637517865/job/23679879915

And not Node specific. Here is the same result with latest pnpm and Node 20 https://github.com/stereobooster/astro-og-canvas-example/actions/runs/8637590696/job/23680117047

**Comment by delucis** [comment]
Ahhh, just realised you don’t have `canvaskit-wasm` as a dependency. Could you try installing it as [mentioned in the README](https://github.com/delucis/astro-og-canvas/tree/latest/packages/astro-og-canvas#installation)?
```sh
pnpm i canvaskit-wasm
```

**Comment by stereobooster** [comment]
Yes indeed. It fixed the problem. Thank you

**Comment by delucis** [comment]
Great! I don’t know if we can improve the error message there as it’s something weird about the package resolution. Thanks for sticking with it 🙌
