### ISSUE TITLE
[bug] Fails to render image for StarLight `src/pages` content

### ISSUE THREAD

**Issue by davidjbradshaw** [delucis/astro-og-canvas#67]
I have a site ([iframe-resizer.com](https://iframe-resizer.com)) built with StarLight. The pages are stored in two locations, `/src/pages/` and `/src/content/docs`. 

On both types of pages the `meta og:image` tags are being correctly inserted into the built pages. However, for pages in the `/scr/pages/` folder the image generator is returning 404, instead of generating the image.

The source for my site can be found here:
https://github.com/iframe-resizer/docs

**Comment by delucis** [comment]
Hi @davidjbradshaw! This is because your open graph image endpoint is only specifying routes for the content in `src/content/docs/`.

The endpoint loads all the docs files here: https://github.com/iframe-resizer/docs/blob/cacd846a2b909ed3bde7fd0363b7ad1b22cbf347/src/pages/og/%5B...slug%5D.ts#L5

You’ll also need to add metadata for your `src/pages/` pages to the `src/pages/og/[...slug].ts` endpoint to tell `astro-og-image` to generate those.

**Comment by davidjbradshaw** [comment]
Doh, my bad. Sorry

**Comment by davidjbradshaw** [comment]
Just had another look at this and I see how it works now, however, I'm still at a loss on how I generate the data from a page created by a `.astro` file?

```jsx
---
import StarlightPage from '@astrojs/starlight/components/StarlightPage.astro';

export const title = 'Commercial Software License Agreement';
export const description = 'Software License Agreement for iframe-resizer.';

---

<StarlightPage frontmatter={{ title, description }}  hasSidebar={false} headings={headings}>
  ...
</StarlightPage>
```
I'm sure a fair few people would find an example useful.

**Comment by davidjbradshaw** [comment]
Actually figured out:
```js
import { OGImageRoute } from "astro-og-canvas";

const pages = await import.meta.glob("/src/pages/**/*.astro", { eager: true })

Object.keys(pages).forEach((path) => {
  if (!('title' in pages[path]) || !('description' in pages[path]))
    delete pages[path]
})

export const { getStaticPaths, GET } = OGImageRoute({
  // Tell us the name of your dynamic route segment.
  // In this case it’s `route`, because the file is named `[...route].ts`.
  param: "route",

  // Pass the glob result to pages
  pages,

  // Extract `title` and `description` from the glob result’s `frontmatter` property
  getImageOptions: (_path, page) => {
    return {
      // Use the page title and description as the image title and description.
      title: page.title,
      description: page.description,
    }
  }
})
```
