### ISSUE TITLE
Support for Astro v2

### ISSUE THREAD

**Issue by fflaten** [delucis/astro-og-canvas#8]
Currently getting peer conflicts when building using `Astro v2.0.0-beta.2` due to `^1.0.0` peer dependency.

**Comment by delucis** [comment]
Same here as for https://github.com/delucis/astro-auto-import/issues/10 — we should be good to loosen that restriction.

I’d welcome a PR to change this line to `^1.0.0 || ^2.0.0-beta`:

https://github.com/delucis/astro-og-canvas/blob/39d74b72ac3e3931e7eadab7f32bd4034fbb1e76/packages/astro-og-canvas/package.json#L42
